export const SITE_CONTEXT = {
  domain: 'mdevtech.vercel.app',
  brand: 'mdevtech Blogs',
  author: 'muneeb1st',
  niche: 'AI tools and workflows for students, freelancers, and small local businesses',
  tone: 'Practical, clear, honest, non-hype, beginner-friendly but not childish.',
  publishingCadence: 'Every 12 hours, but quality must beat speed.',
  rankingGoal: 'Target long-tail keywords with clear search intent and practical usefulness. Do not chase impossible generic keywords.'
};

export function buildSeoPrompt({ cluster, existingPosts = [] }) {
  const relatedTitles = existingPosts.slice(0, 8).map((post) => `- ${post.title}`).join('\n');

  return `You are Hermes, acting as an autonomous SEO research and blogging agent for ${SITE_CONTEXT.brand}.
Author: ${SITE_CONTEXT.author}
Domain: ${SITE_CONTEXT.domain}
Niche: ${SITE_CONTEXT.niche}
Tone: ${SITE_CONTEXT.tone}

Mission:
Create one original, evergreen, SEO-ready blog post that can realistically compete for the target long-tail keyword cluster below. Do not copy from websites. Do not invent fake case studies, rankings, statistics, prices, or competitor claims. Do not use generic motivational fluff. Produce useful, practical content that gives the reader a workflow they can run today.

Target keyword cluster:
${JSON.stringify(cluster, null, 2)}

Existing related posts on the site:
${relatedTitles || '- No existing posts yet.'}

SEO rules:
1. Pick one primary keyword from the cluster. Use it naturally in the title, first 100 words, one H2, meta title, and meta description.
2. Target clear search intent. Explain who the article helps and what problem it solves.
3. Use long-tail keywords naturally. Do not keyword-stuff.
4. Write for humans first, Google second.
5. Put the direct answer and recommended workflow in the first 150 words.
6. Include practical steps, copy-paste prompt templates, examples, mistakes to avoid, tool tradeoffs, and a short checklist.
7. Include one compact comparison table when useful.
8. Include an FAQ with 4-6 real questions searchers may ask.
9. Include 2-4 internal link suggestions to existing or future posts. Each suggestion must have a 'slug' and 'anchor'. Never link to the current post.
10. Include a "what to verify before using this" section for facts, pricing, tool limits, and risky claims.
11. Add 3-6 tags.
12. Add 'claimsNeedingHumanCheck' for facts, tool names, prices, dates, statistics, or claims that should be verified.
13. Add an 'seoScore' from 0 to 1. Aim for 0.88+.
14. Keep the article 1200-1800 words when possible. If Hermes output limits apply, keep it dense and useful.
15. Avoid fake certainty. If you are not sure, say what needs verification.
16. Do not use generic AI filler such as "in today's world", "game-changer", "unlock the power", "look no further", or "this comprehensive guide".
17. Do not mention that the post was generated by AI or that you cannot browse.
18. Make this post clearly different from existing posts. Reuse the site structure, not the same body examples or paragraphs.
19. Prefer low-competition, concrete workflow angles over broad generic keywords.
20. Titles must read like human editorial titles, not database labels. Keep the exact primary keyword, but avoid repeated audience phrases such as "workflow for freelancers" when the keyword already says "for freelancers". Good pattern: "AI Email Templates for Freelancers: Complete Workflow".

Output must be valid JSON only. No markdown fences. No extra explanation.

Required JSON schema:
{
  "title": "SEO title under 65 characters",
  "slug": "stable-url-slug",
  "metaTitle": "45-65 character meta title",
  "metaDescription": "140-160 character meta description",
  "focusKeywords": ["primary keyword", "secondary keyword"],
  "searchIntent": "informational | commercial investigation | transactional | navigational",
  "audience": "students | freelancers | local business owners | small business owners | self-learners",
  "excerpt": "Short summary under 160 characters",
  "body": "Markdown article body with H2 headings, direct answer, practical steps, prompt templates, examples, verification section, checklist, and conclusion. Minimum 1200 words.",
  "faq": [{"question": "Question?", "answer": "Short helpful answer"}],
  "internalLinks": [{"slug": "future-related-slug", "anchor": "Anchor text"}],
  "tags": ["tag"],
  "jsonLd": {
    "headline": "Article title",
    "description": "Meta description",
    "keywords": ["keywords"],
    "articleSection": "AI automation"
  },
  "seoScore": 0.88,
  "claimsNeedingHumanCheck": ["Any claim that needs verification"]
}

Before writing, silently choose the best ranking angle:
- low competition long-tail intent
- practical implementation
- beginner mistakes
- tool stack
- measurable outcome
- clear FAQ
- original task-specific examples that are not copied from other sites

Now write the JSON.`;
}

function sentenceCase(value = '') {
  return String(value).charAt(0).toUpperCase() + String(value).slice(1);
}

function titleCase(value = '') {
  const keepUpper = new Set(['ai', 'faq', 'seo', 'cv', 'llm', 'crm']);
  const smallWords = new Set(['for', 'and', 'or', 'to', 'of', 'in', 'on', 'with']);
  const words = String(value)
    .trim()
    .replace(/\s+/g, ' ')
    .split(' ');

  return words
    .map((word, index) => {
      const lower = word.toLowerCase();
      if (keepUpper.has(lower)) return lower.toUpperCase();
      if (index > 0 && smallWords.has(lower)) return lower;
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join(' ');
}

export function buildNaturalTitle(primary = '', audience = '') {
  const cleanPrimary = titleCase(primary);
  const lower = String(primary).toLowerCase();
  const suffix = lower.includes('template')
    ? 'Reusable Workflow'
    : lower.includes('builder') || lower.includes('maker') || lower.includes('planner')
      ? 'Step-by-Step Workflow'
      : lower.includes('tools')
        ? 'Practical Workflow'
        : 'Complete Workflow';

  return `${cleanPrimary}: ${suffix}`;
}

export function buildNaturalMetaTitle(primary = '', audience = '') {
  const title = buildNaturalTitle(primary, audience);
  if (title.length <= 65) return title;
  return `${titleCase(primary)} Workflow`;
}

export function buildNaturalMetaDescription(primary = '') {
  return `Learn a practical ${primary} workflow with tools, prompt templates, verification checks, and common mistakes to avoid before you reuse it.`;
}

function primaryAlreadyNamesAudience(primary = '', audience = '') {
  if (!audience) return false;
  const primaryLower = String(primary).toLowerCase();
  const audienceLower = String(audience).toLowerCase();
  return primaryLower.includes(`for ${audienceLower}`);
}

export function buildNaturalExcerpt(primary = '', audience = '') {
  const audiencePhrase = audience && !primaryAlreadyNamesAudience(primary, audience) ? ` for ${audience}` : '';
  if (!audiencePhrase) {
    return `A practical ${primary} workflow with saved prompts, tool choices, and verification checks before you reuse the output.`;
  }
  return `A practical ${primary} workflow${audiencePhrase}, with tools, prompt templates, and verification checks.`;
}

function renderBullets(items = []) {
  return items.map((item) => `- ${item}`).join('\n');
}

function buildFallbackPlan({ cluster, primary, audience, angle }) {
  const workflow = Array.isArray(cluster.workflow) && cluster.workflow.length
    ? cluster.workflow
    : ['Define the task', 'Draft with AI', 'Review the output', 'Save the template'];
  const tools = Array.isArray(cluster.tools) && cluster.tools.length ? cluster.tools : ['LLM', 'Google Docs', 'Notion'];
  const primaryLower = primary.toLowerCase();

  if (primaryLower.includes('proposal')) {
    return {
      outcomeExamples: [
        'A six-section proposal for a website redesign lead who already shared goals, budget range, and deadline',
        'A short discovery-to-proposal outline for a freelance copywriting client',
        'A reusable scope, timeline, deliverables, and next-step block you can paste into Google Docs',
        'A polite follow-up email that sends the proposal without sounding automated'
      ],
      toolRows: [
        ['Client brief cleanup', tools[0] || 'LLM', 'Turns messy notes into requirements, risks, questions, and proposal sections'],
        ['Proposal drafting', tools[1] || 'Google Docs', 'Keeps the final document editable and easy to personalize'],
        ['Template library', tools[2] || 'Notion', 'Stores winning sections, objections, and client-specific examples'],
        ['Signature or approval', tools[3] || 'DocuSign', 'Moves the client from review to clear next action']
      ],
      steps: [
        {
          title: workflow[0] || 'Write the client brief',
          detail: 'Start by turning the client conversation into a clean brief. Include the client goal, the business problem, the requested deliverables, known constraints, deadline, decision maker, and any phrases the client used. This gives AI real context instead of forcing it to guess. For a freelancer, this step matters because the proposal should sound like a response to the client, not a generic sales page.',
          prompt: `Turn these discovery notes into a clean client brief for a proposal. Separate goals, deliverables, timeline, budget signals, objections, missing questions, and success criteria. Keep the wording plain and do not invent details.\n\nNotes:\n[paste notes]`,
          check: 'Make sure every claim in the brief came from the client or your own verified notes.'
        },
        {
          title: workflow[1] || 'Create proposal sections',
          detail: 'Ask AI for a structure before asking for polished copy. A strong proposal usually needs a summary, problem statement, recommended approach, deliverables, timeline, investment, proof or relevant experience, and next steps. Keeping the sections consistent makes the template reusable while leaving enough room for customization.',
          prompt: `Create a proposal outline for this client brief. Use these sections: summary, problem, recommended approach, deliverables, timeline, investment, proof, assumptions, next steps. Add one sentence explaining what each section must prove to the client.`,
          check: 'Remove sections that do not match the client stage. A warm referral may need less proof than a cold lead.'
        },
        {
          title: workflow[2] || 'Add timeline and pricing',
          detail: 'Use AI to draft options, but keep pricing decisions human. Ask for clear package language, assumptions, exclusions, and timeline milestones. This prevents scope confusion later. If you offer one package, ask AI to sharpen why that package is the best fit. If you offer three options, make the tradeoffs easy to compare.',
          prompt: `Draft the timeline, deliverables, assumptions, and pricing explanation for this proposal. Use confident but honest language. Do not invent guarantees. Make exclusions clear so the client understands what is not included.`,
          check: 'Verify numbers, dates, taxes, revision limits, licensing, and payment terms before sending.'
        },
        {
          title: workflow[3] || 'Personalize before sending',
          detail: 'The last pass should add the client-specific details that AI cannot know by default: their brand language, exact pain points, names, objections, and preferred next step. This is where the proposal stops sounding like a template. Read it aloud once and remove anything you would not naturally say to the client.',
          prompt: `Rewrite this proposal so it sounds specific to the client. Keep the structure, but add references to their goal, their audience, their constraints, and the next decision they need to make. Flag any sentence that sounds generic.`,
          check: 'Send only after you can point to at least five details that are unique to this client.'
        }
      ],
      mistakes: [
        'Sending the first AI draft without adding client-specific proof',
        'Letting AI invent outcomes, timelines, guarantees, or pricing logic',
        'Using vague deliverables like "strategy" without defining what the client receives',
        'Hiding assumptions and exclusions until after the client accepts',
        'Forgetting a single clear next step at the end of the proposal'
      ],
      verification: [
        'Client name, project scope, dates, price, taxes, and payment schedule',
        'Claims about previous work, results, certifications, or availability',
        'Legal language, ownership rights, cancellation terms, and revision limits',
        'Any tool-generated promise that sounds like a guaranteed business outcome'
      ]
    };
  }

  if (primaryLower.includes('social media') || primaryLower.includes('content calendar')) {
    return {
      outcomeExamples: [
        'A seven-day Instagram and Facebook calendar for a local bakery promoting weekend specials',
        'Three post angles for a service business that wants calls, not just likes',
        'Caption drafts that reuse real customer questions, offers, and seasonal moments',
        'A weekly review checklist for checking accuracy, tone, and scheduling'
      ],
      toolRows: [
        ['Idea generation', tools[0] || 'LLM', 'Turns offers, FAQs, and events into post angles'],
        ['Scheduling', tools[1] || 'Meta Business Suite', 'Publishes Facebook and Instagram posts from one place'],
        ['Design', tools[2] || 'Canva', 'Creates simple branded visuals without a design team'],
        ['Queue management', tools[3] || 'Buffer', 'Helps keep posts moving when one channel is not enough']
      ],
      steps: [
        {
          title: workflow[0] || 'List offers',
          detail: 'Start with real business inputs: current offers, opening hours, seasonal events, customer questions, photos you already have, and products or services with good margins. AI performs better when it gets raw material from the business instead of guessing what customers care about.',
          prompt: `Create a one-week content input list for a local business. Use these offers, FAQs, events, and customer objections. Group ideas by goal: awareness, trust, direct offer, education, and repeat visit.\n\nBusiness notes:\n[paste notes]`,
          check: 'Remove anything that mentions an offer, date, product, or policy you cannot verify.'
        },
        {
          title: workflow[1] || 'Generate post angles',
          detail: 'Ask AI for angles before full captions. Good angles include customer questions, behind-the-scenes moments, simple comparisons, before-and-after explanations, limited-time offers, and local relevance. Pick the strongest seven before writing captions so the calendar has variety.',
          prompt: `Generate 12 social media post angles from this business input. For each angle, include the target customer, hook, post format, call to action, and why it fits this week. Avoid generic motivational posts.`,
          check: 'Keep a mix of helpful, proof-based, local, and offer-driven posts.'
        },
        {
          title: workflow[2] || 'Write captions',
          detail: 'Now write captions in batches. Give AI the chosen angles, the brand voice, words to avoid, platform, and desired call to action. Ask for shorter captions first; small businesses often need clarity more than cleverness. Save the best lines as reusable caption blocks.',
          prompt: `Write captions for these seven post angles. Keep them clear, local, and useful. Include a short hook, one useful detail, and one call to action. Avoid hype, fake scarcity, and overused AI phrases.`,
          check: 'Read each caption as the business owner. If it sounds like a generic brand, rewrite it.'
        },
        {
          title: workflow[3] || 'Schedule and review',
          detail: 'Before scheduling, check every caption, image, link, tag, and date. Then schedule posts in Meta Business Suite, Buffer, or the tool the business already uses. After the week ends, review which posts got useful actions: messages, calls, saves, comments, or clicks.',
          prompt: `Create a final review checklist for this one-week calendar. Include accuracy checks, visual checks, scheduling checks, and post-week performance notes.`,
          check: 'Do not judge only by likes. Track the action the business actually wanted.'
        }
      ],
      mistakes: [
        'Asking AI for random post ideas without giving offers, FAQs, or local context',
        'Scheduling captions with wrong dates, hours, prices, or unavailable products',
        'Posting seven sales posts in a row with no helpful or trust-building content',
        'Using generic hooks that could belong to any business',
        'Never reviewing which posts created messages, calls, bookings, or visits'
      ],
      verification: [
        'Opening hours, offer dates, menu/service details, prices, addresses, and phone numbers',
        'Image rights, brand colors, logos, and customer photo permissions',
        'Platform rules for promotions, claims, health content, or before-and-after posts',
        'Whether the call to action matches what staff can actually handle that week'
      ]
    };
  }

  if (primaryLower.includes('resume') || primaryLower.includes('cv')) {
    return {
      outcomeExamples: [
        'A one-page student resume that turns class projects, volunteer work, internships, and part-time jobs into honest bullet points',
        'Three tailored resume versions for a software internship, campus role, and entry-level support position',
        'A skills section that separates tools actually used from tools only watched in tutorials',
        'A final review checklist that catches invented metrics, inflated titles, and missing dates before sending'
      ],
      toolRows: [
        ['Experience inventory', tools[0] || 'LLM', 'Turns raw student activities into categorized projects, skills, coursework, and achievements'],
        ['Resume drafting', tools[1] || 'Google Docs', 'Keeps bullet points editable so the student can correct facts before exporting'],
        ['Layout polish', tools[2] || 'Canva', 'Helps create a clean one-page resume without hiding weak content behind decoration'],
        ['Profile matching', tools[3] || 'LinkedIn', 'Checks whether resume wording matches public profile, projects, and role targets']
      ],
      steps: [
        {
          title: workflow[0] || 'List experience',
          detail: 'Start with an evidence inventory, not a resume template. Ask the student to list courses, projects, labs, assignments, competitions, volunteer work, part-time jobs, societies, tools used, links, and outcomes. Include weak-looking experience too, because AI can often turn simple work into clearer responsibility statements without inventing anything. The rule is strict: if the student cannot explain it in an interview, it does not belong on the resume.',
          prompt: `Help me build a student resume evidence inventory. Organize these notes into education, projects, coursework, skills, volunteer work, part-time experience, achievements, links, and missing details. Do not invent dates, metrics, job titles, or technologies.\n\nRaw notes:\n[paste notes]`,
          check: 'Every item should be traceable to a real project, class, role, certificate, link, or activity.'
        },
        {
          title: workflow[1] || 'Draft bullets',
          detail: 'Draft bullets from evidence using action, task, tool, and outcome. Students often have limited experience, so the goal is clarity, not fake seniority. A bullet like "Built a Java calculator using OOP concepts for a class project" is better than "Engineered scalable fintech solutions" when the second sentence is not true. Ask AI for several versions, then choose the most honest and specific one.',
          prompt: `Turn this student experience into resume bullet points. Use action verbs, tools used, project context, and honest outcomes. Keep each bullet one line where possible. Mark weak, vague, or unverifiable bullets instead of exaggerating them.`,
          check: 'Remove inflated verbs, invented numbers, fake leadership claims, and tools the student cannot discuss.'
        },
        {
          title: workflow[2] || 'Check facts',
          detail: 'Before tailoring the resume, run a fact audit. Check dates, degree name, institution spelling, project links, GitHub links, certificates, tool names, and whether each skill is actually demonstrated somewhere. This is where many AI resumes fail: the formatting looks good, but the facts do not survive a recruiter call or technical interview.',
          prompt: `Audit this resume draft for risky claims. Create three lists: verified facts, claims needing evidence, and lines that sound exaggerated for a student. Suggest honest rewrites for the risky lines.`,
          check: 'The final resume should contain no claim that depends only on AI wording.'
        },
        {
          title: workflow[3] || 'Tailor to job',
          detail: 'Tailor only after the base resume is accurate. Paste the job description and ask AI to map real student evidence to the required skills. Do not copy keywords blindly. If the job asks for React and the student only used basic HTML/CSS, the resume should not pretend React experience. Instead, it can emphasize learning ability, relevant coursework, or a related project.',
          prompt: `Compare this student resume with the job description. Match only real experience to the role requirements. Suggest wording changes, missing evidence, and a priority order for sections. Do not add skills or experience that are not in the resume evidence inventory.`,
          check: 'The tailored version must still be truthful if the interviewer asks for details about every bullet.'
        }
      ],
      mistakes: [
        'Letting AI invent internship duties, metrics, certifications, or job titles',
        'Using a resume design that looks polished but hides weak or vague content',
        'Adding every tool keyword from a job description even when the student has not used it',
        'Writing bullets so broad that they could belong to any student',
        'Forgetting to check links, dates, spelling, file name, and PDF formatting before sending'
      ],
      verification: [
        'Degree name, university name, dates, GPA if listed, certificates, and project links',
        'Whether every tool in the skills section appears in a real project, course, or experience',
        'Whether metrics, achievements, and leadership claims are true and explainable',
        'Whether the resume matches the student LinkedIn, GitHub, portfolio, and application target'
      ]
    };
  }

  return {
    outcomeExamples: [
      `A finished ${primary} asset based on real questions, notes, or business inputs`,
      `A reviewed workflow that ${audience} can repeat without starting from scratch`,
      `A saved prompt template with assumptions and risky claims clearly marked`,
      `A practical checklist for publishing, sending, studying, or handing off the result`
    ],
    toolRows: tools.slice(0, 4).map((tool, index) => [
      workflow[index] || `Workflow stage ${index + 1}`,
      tool,
      [
        'Captures the raw input before AI starts drafting',
        'Keeps the draft editable and easy to review',
        'Helps organize reusable examples, questions, and constraints',
        'Supports the final publish, send, or handoff step'
      ][index] || 'Keeps this stage practical, editable, and easy to verify'
    ]),
    steps: workflow.slice(0, 4).map((step, index) => ({
      title: step,
      detail: [
        `Start by collecting the source material for "${primary}": real notes, customer questions, assignment details, client constraints, examples, and anything that must not be changed. This gives AI a grounded input instead of forcing it to invent context. For ${audience}, the best inputs usually come from repeated questions, support messages, client notes, class requirements, product details, or previous work that already performed well. Do not ask for a draft until those inputs are in one place.`,
        `Group the input into a simple structure before asking for polished writing. For ${audience}, this means separating facts, assumptions, missing details, examples, and the exact output format. A useful structure makes review faster because you can see what came from the source material and what came from the model. If a section has no supporting input, mark it as missing instead of letting AI fill the gap with a confident guess.`,
        `Draft the first usable version with a narrow prompt. Ask AI to mark assumptions, uncertainty, risky claims, and anything that needs a human decision. A good draft should make review easier, not replace review. Keep the output focused on the channel where it will be used, such as a website page, client document, study note, email, or publishing checklist. If the draft tries to solve too many jobs at once, split it into smaller outputs.`,
        `Publish, send, or save the final version only after the verification pass. Store the final prompt and edited output together so the next similar task starts from a proven template.`
      ][index] || `${sentenceCase(step)} should produce a concrete output that can be reviewed and reused.`,
      prompt: [
        `Collect the inputs for this ${primary} workflow. Ask me for missing details, then organize what I provide into facts, assumptions, audience details, constraints, examples, and risks.`,
        `Turn these inputs into a clear structure for ${primary}. Group related items, flag missing information, and recommend the best output format for ${audience}.`,
        `Draft the ${primary} output using the structure below. Keep it practical, specific, and easy to verify. Mark every assumption and every claim that needs checking.`,
        `Create a final review and reuse checklist for this ${primary} workflow. Include accuracy checks, tone checks, formatting checks, and what to save for next time.`
      ][index] || `Help me complete this ${primary} workflow stage: ${step}.`,
      check: [
        'Confirm the source material is real, specific, and safe to use with the chosen tool.',
        'Confirm the structure matches the searcher intent and does not skip key questions.',
        'Confirm the draft contains no invented facts, prices, dates, results, or guarantees.',
        'Confirm the final version is saved with its prompt, checklist, and verified output.'
      ][index] || 'Confirm the output matches your real task, audience, and constraints.'
    })),
    mistakes: [
      'Starting with a vague prompt and expecting a polished result',
      'Using a tool because it is popular instead of because it fits the task',
      'Skipping verification for dates, names, prices, facts, or policies',
      'Saving no reusable template after the work is done'
    ],
    verification: [
      'Tool names, pricing, limits, and terms',
      'Facts, dates, names, numbers, citations, and policy-sensitive claims',
      'Whether the final output matches the audience and channel',
      'Whether private or client data is safe to upload to the chosen tool'
    ]
  };
}

export function buildFallbackPost({ cluster, now = new Date(), existingPosts = [] }) {
  const primary = cluster.primaryKeyword;
  const audience = cluster.audience || 'students and freelancers';
  const intent = cluster.searchIntent || 'informational';
  const secondary = (cluster.secondaryKeywords || []).slice(0, 3);
  const angle = cluster.articleAngle || 'practical implementation guide';
  const workflow = Array.isArray(cluster.workflow) && cluster.workflow.length
    ? cluster.workflow
    : ['Define the task', 'Draft with AI', 'Review the output', 'Save the template'];
  const tools = Array.isArray(cluster.tools) && cluster.tools.length ? cluster.tools : ['LLM', 'Google Docs', 'Notion'];
  const plan = buildFallbackPlan({ cluster, primary, audience, angle });
  const workflowSteps = plan.steps.map((step, index) => `## Step ${index + 1}: ${step.title}

${step.detail}

Copy-paste prompt:

\`\`\`
${step.prompt}
\`\`\`

Verification check: ${step.check}`).join('\n\n');
  const toolRows = plan.toolRows.map((row) => `| ${row[0]} | ${row[1]} | ${row[2]} |`).join('\n');
  const topicSpecificBrief = [
    `For ${primary}, collect source material that names the exact task: ${workflow.join(', ')}.`,
    `Useful inputs include ${secondary.length ? secondary.join(', ') : 'real examples, notes, constraints, and review rules'} plus screenshots, old drafts, customer or class questions, and the channel where the final output will be used.`,
    `A ${audience} workflow should mention the actual tools in the stack — ${tools.join(', ')} — only where they help the job, not as decoration.`,
    `The final draft should be reviewed against ${angle.toLowerCase()}, because that is the reason this keyword deserves its own article instead of being merged into a generic AI tools guide.`,
    `If the work involves ${workflow[0]?.toLowerCase() || 'collecting input'}, save one example of a good input. If it involves ${workflow[1]?.toLowerCase() || 'drafting'}, save one before-and-after rewrite. If it involves ${workflow[2]?.toLowerCase() || 'review'}, save the checklist that caught mistakes.`,
    `For searchers comparing ${secondary[0] || primary} with ${secondary[1] || 'general AI tools'}, the deciding factor is not feature count. The deciding factor is whether the workflow produces a result they can trust without hours of cleanup.`
  ].join('\n\n');

  const baseSlug = cluster.slug || primary.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const slug = baseSlug;

  const title = buildNaturalTitle(primary, audience);
  const metaTitle = buildNaturalMetaTitle(primary, audience);
  const metaDescription = buildNaturalMetaDescription(primary);
  const excerpt = buildNaturalExcerpt(primary, audience);

  const body = `## ${primary}: a field-ready workflow

${sentenceCase(primary)} should produce a concrete asset, not a vague chat transcript. For ${audience}, the useful version is built around ${angle}. Start with the material that already exists, decide what the final output must do, draft in one narrow pass, then review the risky details before anyone uses it.

Search intent: ${intent}. The reader wants a usable process they can copy today, so the first move is not choosing a fancy app. The first move is defining the input, output, review owner, and reuse point.

For this topic, the operating sequence is ${workflow.map((step) => step.toLowerCase()).join(' → ')}. Keep the sequence visible while drafting so the article, template, or deliverable does not drift into general AI advice.

## Where ${primary} creates value

The ranking angle is ${angle}. That matters because searchers are usually trying to finish a specific job under time pressure. They do not need a broad tool roundup; they need a repeatable path from messy source material to a reviewed result.

Practical outputs this workflow can create:

${renderBullets(plan.outcomeExamples)}

Before opening an AI tool, write one sentence that defines success for the output. Example: "After this workflow, I should have a reviewed ${primary} draft that is safe to send, publish, study from, or save as a template." That sentence keeps the work grounded and makes the review step easier.

Topic-specific input brief:

${topicSpecificBrief}

## Tool stack for ${primary}

| Workflow stage | Tool to consider | Why it helps |
|----------------|------------------|--------------|
${toolRows}

Use the smallest stack that covers capture, drafting, review, and storage. If ${tools[0] || 'an LLM'} and ${tools[1] || 'a document editor'} are enough, do not add more software. Extra tools create more places for wrong facts, outdated copies, or private data leaks.

${workflowSteps}

After each step, save the better wording, useful examples, and failed prompts. Those notes become the source material for the next run and make the workflow more specific over time.

## What to verify before using this workflow

Run this verification check before relying on the output:

${renderBullets(plan.verification)}

Also check whether the output exposes private student, client, customer, or business data. If it does, remove sensitive details before pasting into external tools or keep the work inside software the user already trusts.

The verification pass should leave evidence. Keep a short note saying what was checked, what was changed, and what still needs a human decision. That record is useful if the same ${primary} task returns next week.

## Reusable prompt template for ${primary}

Copy-paste prompt template:

\`\`\`
You are helping with ${primary} for ${audience}.

Goal: [describe the exact outcome]
Raw material: [paste notes, questions, requirements, examples, links, constraints]
Output format: [document, checklist, email, table, study aid, website copy]
Audience context: [who will use or read it]
Known risks: [facts, dates, prices, claims, privacy issues]
Tone: clear, practical, non-hype

Work in this order:
1. Identify missing information before drafting.
2. Organize the raw material into sections.
3. Draft the output with assumptions clearly marked.
4. Create a verification checklist for anything uncertain.
5. Suggest what should be saved as a reusable template.
\`\`\`

If the first answer is generic, do not ask for "make it better." Add sharper inputs: real examples, banned wording, audience details, length limits, and the exact decision the output should support.

## Store the reviewed version

Template record:

\`\`\`
# Workflow: ${primary}
# Use case: [specific situation]
# Best prompt: [paste the refined prompt]
# Reviewed output: [paste the corrected result]
# Checks completed: [facts, tone, formatting, privacy, links]
# Next improvement: [what to add next time]
\`\`\`

This storage step is part of the workflow, not admin work. Without it, ${audience} repeat the same prompt mistakes and review from zero every time. With it, each run improves the next run.

Keep the saved version close to the tool where the work happens. A restaurant owner might keep menu description prompts beside product photos; a student might keep study prompts beside class notes; a freelancer might keep client templates beside project folders. The exact app matters less than retrieval. If the reviewed version cannot be found in thirty seconds, the system will not survive busy weeks.

## Common mistakes to avoid

${renderBullets(plan.mistakes)}

The fix is to make the input more concrete before asking for polish. Add source notes, examples, constraints, and the channel where the output will live. Then ask the model to mark uncertainty instead of hiding it.

A weak run usually leaves clues: the draft sounds like it could fit any business, class, or client; the tool invents confident details; or the final text has no owner for review. Treat those clues as process problems. Improve the brief, narrow the output, and add a verification rule before generating another version.

## Final checklist before publishing or sending

- [ ] Does the output solve the exact ${primary} task?
- [ ] Is "${primary}" used naturally in the title, opening, H2, and meta title?
- [ ] Are the examples specific to ${audience} and the selected use case?
- [ ] Did you remove invented facts, fake numbers, and unsupported claims?
- [ ] Is there a copy-paste prompt or prompt template saved for reuse?
- [ ] Are verification checks written next to the final output?
- [ ] Are related internal links included without linking to this same post?
- [ ] Would a beginner know the next action after reading it?

## Bottom line

${sentenceCase(primary)} is worth using when it turns repeated work into a checked process. The process is simple: define the source material, draft with constraints, review the risky details, and save the improved version. That is how ${audience} get speed without publishing sloppy AI output.

Do not measure this workflow only by how fast the first draft appears. Measure whether the final version is accurate, specific, reusable, and safe for the channel where it will be used. If those four conditions are met, the workflow can become a small operating system for repeated work instead of another disposable AI chat.

### Related guides on mdevtech Blogs

${existingPosts.length > 0
  ? existingPosts.slice(0, 3).map((p) => `- [${p.title}](/posts/${p.slug}/)`).join('\n')
  : '- [AI tools for students: note-taking and research workflow](/posts/ai-tools-students-note-taking-research/)\n- [AI proposal writing workflow for freelancers](/posts/ai-proposal-writing-freelancers/)\n- [Local business AI content calendar](/posts/ai-content-calendar-local-business/)'}

`;

  const relatedPosts = existingPosts.slice(0, 2).map((p) => ({
    slug: p.slug,
    anchor: p.title
  }));

  // Add fallback internal links if no existing posts
  if (relatedPosts.length < 2) {
    relatedPosts.push(
      { slug: 'ai-tools-students-note-taking-research', anchor: 'AI tools for students: note-taking and research workflow' },
      { slug: 'ai-proposal-writing-freelancers', anchor: 'AI proposal writing workflow for freelancers' }
    );
  }

  return {
    title,
    slug,
    metaTitle,
    metaDescription,
    focusKeywords: [primary, ...secondary.slice(0, 2)],
    searchIntent: intent,
    audience,
    excerpt,
    body,
    faq: [
      {
        question: `What is the best way to use ${primary} effectively?`,
        answer: `Use ${primary} for a specific, repeatable task with clear constraints. Start with the workflow above, verify every output, and save the refined prompt as a template for future use.`
      },
      {
        question: `Can beginners use AI workflows for ${primary} without technical skills?`,
        answer: `Yes. Beginners should start with the prompt template above, use free-tier tools like ChatGPT or Claude, and always verify AI output before relying on it. No coding required.`
      },
      {
        question: `What are the most common mistakes to avoid with ${primary}?`,
        answer: `Avoid vague prompts without context, publishing unverified AI output, targeting generic keywords instead of specific workflows, skipping the human review step, and trying to use five tools when one well-prompted tool suffices.`
      },
      {
        question: `Which tools are best for ${primary} and do I need paid plans?`,
        answer: `Use a general-purpose LLM (ChatGPT, Claude, or Gemini) plus a notes app. All have free tiers sufficient for individual use. Specialized tools like Perplexity or Canva are optional. Verify current free tier limits before relying on them.`
      },
      {
        question: `How long does it take to build and run a ${primary} workflow?`,
        answer: `First time: 30-60 minutes including prompt refinement and verification. After saving as a template: 5-10 minutes per use. The time investment pays off after 2-3 uses.`
      },
      {
        question: `How do I know if my ${primary} output is good enough to use?`,
        answer: `Run the verification checklist: fact-check all tool names and prices, confirm tone matches your voice, ensure every step is actionable, check formatting, and remove any hallucinated features or made-up examples.`
      }
    ],
    internalLinks: relatedPosts.slice(0, 3),
    tags: ['AI automation', audience, primary, 'workflow', 'productivity', 'AI tools'],
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      headline: title,
      description: metaDescription,
      keywords: [primary, ...secondary.slice(0, 2)],
      articleSection: 'AI automation'
    },
    seoScore: 0.9,
    claimsNeedingHumanCheck: [
      'Verify tool names, prices, and feature availability before publishing - free tiers change frequently.',
      'Check that free tier limits mentioned (Zapier, Make, Cursor, etc.) are still accurate as of publication date.',
      'Confirm any statistics or benchmarks cited in the article.',
      'Verify that the prompt template structure works with current model versions.',
      'Ensure internal link slugs match actual published posts.'
    ]
  };
}
