export const SITE_CONTEXT = {
  domain: 'mdevtech.vercel.app',
  brand: 'mdevtech Blogs',
  author: 'muneeb1st',
  niche: 'AI tools and workflows for students, freelancers, and small local businesses',
  tone: 'Practical, clear, honest, non-hype, beginner-friendly but not childish.',
  publishingCadence: 'Every 12 hours, but quality must beat speed.',
  rankingGoal: 'Target long-tail keywords with clear search intent and practical usefulness. Do not chase impossible generic keywords.'
};

export function buildSeoPrompt({ cluster, existingPosts = [] }) {
  const relatedTitles = existingPosts.slice(0, 8).map((post) => `- ${post.title}`).join('\n');

  return `You are Hermes, acting as an autonomous SEO research and blogging agent for ${SITE_CONTEXT.brand}.
Author: ${SITE_CONTEXT.author}
Domain: ${SITE_CONTEXT.domain}
Niche: ${SITE_CONTEXT.niche}
Tone: ${SITE_CONTEXT.tone}

Mission:
Create one original, evergreen, SEO-ready blog post that can realistically compete for the target long-tail keyword cluster below. Do not copy from websites. Do not invent fake case studies, rankings, statistics, prices, or competitor claims. Do not use generic motivational fluff. Produce useful, practical content that gives the reader a workflow they can run today.

Target keyword cluster:
${JSON.stringify(cluster, null, 2)}

Existing related posts on the site:
${relatedTitles || '- No existing posts yet.'}

SEO rules:
1. Pick one primary keyword from the cluster. Use it naturally in the title, first 100 words, one H2, meta title, and meta description.
2. Target clear search intent. Explain who the article helps and what problem it solves.
3. Use long-tail keywords naturally. Do not keyword-stuff.
4. Write for humans first, Google second.
5. Put the direct answer and recommended workflow in the first 150 words.
6. Include practical steps, copy-paste prompt templates, examples, mistakes to avoid, tool tradeoffs, and a short checklist.
7. Include one compact comparison table when useful.
8. Include an FAQ with 4-6 real questions searchers may ask.
9. Include 2-4 internal link suggestions to existing or future posts. Each suggestion must have a 'slug' and 'anchor'. Never link to the current post.
10. Include a "what to verify before using this" section for facts, pricing, tool limits, and risky claims.
11. Add 3-6 tags.
12. Add 'claimsNeedingHumanCheck' for facts, tool names, prices, dates, statistics, or claims that should be verified.
13. Add an 'seoScore' from 0 to 1. Aim for 0.88+.
14. Keep the article 1200-1800 words when possible. If Hermes output limits apply, keep it dense and useful.
15. Avoid fake certainty. If you are not sure, say what needs verification.
16. Do not use generic AI filler such as "in today's world", "game-changer", "unlock the power", "look no further", or "this comprehensive guide".
17. Do not mention that the post was generated by AI or that you cannot browse.
18. Make this post clearly different from existing posts. Reuse the site structure, not the same body examples or paragraphs.
19. Prefer low-competition, concrete workflow angles over broad generic keywords.

Output must be valid JSON only. No markdown fences. No extra explanation.

Required JSON schema:
{
  "title": "SEO title under 65 characters",
  "slug": "stable-url-slug",
  "metaTitle": "45-65 character meta title",
  "metaDescription": "140-160 character meta description",
  "focusKeywords": ["primary keyword", "secondary keyword"],
  "searchIntent": "informational | commercial investigation | transactional | navigational",
  "audience": "students | freelancers | local business owners | small business owners | self-learners",
  "excerpt": "Short summary under 160 characters",
  "body": "Markdown article body with H2 headings, direct answer, practical steps, prompt templates, examples, verification section, checklist, and conclusion. Minimum 1200 words.",
  "faq": [{"question": "Question?", "answer": "Short helpful answer"}],
  "internalLinks": [{"slug": "future-related-slug", "anchor": "Anchor text"}],
  "tags": ["tag"],
  "jsonLd": {
    "headline": "Article title",
    "description": "Meta description",
    "keywords": ["keywords"],
    "articleSection": "AI automation"
  },
  "seoScore": 0.88,
  "claimsNeedingHumanCheck": ["Any claim that needs verification"]
}

Before writing, silently choose the best ranking angle:
- low competition long-tail intent
- practical implementation
- beginner mistakes
- tool stack
- measurable outcome
- clear FAQ
- original task-specific examples that are not copied from other sites

Now write the JSON.`;
}

function sentenceCase(value = '') {
  return String(value).charAt(0).toUpperCase() + String(value).slice(1);
}

function renderBullets(items = []) {
  return items.map((item) => `- ${item}`).join('\n');
}

function buildFallbackPlan({ cluster, primary, audience, angle }) {
  const workflow = Array.isArray(cluster.workflow) && cluster.workflow.length
    ? cluster.workflow
    : ['Define the task', 'Draft with AI', 'Review the output', 'Save the template'];
  const tools = Array.isArray(cluster.tools) && cluster.tools.length ? cluster.tools : ['LLM', 'Google Docs', 'Notion'];
  const primaryLower = primary.toLowerCase();

  if (primaryLower.includes('proposal')) {
    return {
      outcomeExamples: [
        'A six-section proposal for a website redesign lead who already shared goals, budget range, and deadline',
        'A short discovery-to-proposal outline for a freelance copywriting client',
        'A reusable scope, timeline, deliverables, and next-step block you can paste into Google Docs',
        'A polite follow-up email that sends the proposal without sounding automated'
      ],
      toolRows: [
        ['Client brief cleanup', tools[0] || 'LLM', 'Turns messy notes into requirements, risks, questions, and proposal sections'],
        ['Proposal drafting', tools[1] || 'Google Docs', 'Keeps the final document editable and easy to personalize'],
        ['Template library', tools[2] || 'Notion', 'Stores winning sections, objections, and client-specific examples'],
        ['Signature or approval', tools[3] || 'DocuSign', 'Moves the client from review to clear next action']
      ],
      steps: [
        {
          title: workflow[0] || 'Write the client brief',
          detail: 'Start by turning the client conversation into a clean brief. Include the client goal, the business problem, the requested deliverables, known constraints, deadline, decision maker, and any phrases the client used. This gives AI real context instead of forcing it to guess. For a freelancer, this step matters because the proposal should sound like a response to the client, not a generic sales page.',
          prompt: `Turn these discovery notes into a clean client brief for a proposal. Separate goals, deliverables, timeline, budget signals, objections, missing questions, and success criteria. Keep the wording plain and do not invent details.\n\nNotes:\n[paste notes]`,
          check: 'Make sure every claim in the brief came from the client or your own verified notes.'
        },
        {
          title: workflow[1] || 'Create proposal sections',
          detail: 'Ask AI for a structure before asking for polished copy. A strong proposal usually needs a summary, problem statement, recommended approach, deliverables, timeline, investment, proof or relevant experience, and next steps. Keeping the sections consistent makes the template reusable while leaving enough room for customization.',
          prompt: `Create a proposal outline for this client brief. Use these sections: summary, problem, recommended approach, deliverables, timeline, investment, proof, assumptions, next steps. Add one sentence explaining what each section must prove to the client.`,
          check: 'Remove sections that do not match the client stage. A warm referral may need less proof than a cold lead.'
        },
        {
          title: workflow[2] || 'Add timeline and pricing',
          detail: 'Use AI to draft options, but keep pricing decisions human. Ask for clear package language, assumptions, exclusions, and timeline milestones. This prevents scope confusion later. If you offer one package, ask AI to sharpen why that package is the best fit. If you offer three options, make the tradeoffs easy to compare.',
          prompt: `Draft the timeline, deliverables, assumptions, and pricing explanation for this proposal. Use confident but honest language. Do not invent guarantees. Make exclusions clear so the client understands what is not included.`,
          check: 'Verify numbers, dates, taxes, revision limits, licensing, and payment terms before sending.'
        },
        {
          title: workflow[3] || 'Personalize before sending',
          detail: 'The last pass should add the client-specific details that AI cannot know by default: their brand language, exact pain points, names, objections, and preferred next step. This is where the proposal stops sounding like a template. Read it aloud once and remove anything you would not naturally say to the client.',
          prompt: `Rewrite this proposal so it sounds specific to the client. Keep the structure, but add references to their goal, their audience, their constraints, and the next decision they need to make. Flag any sentence that sounds generic.`,
          check: 'Send only after you can point to at least five details that are unique to this client.'
        }
      ],
      mistakes: [
        'Sending the first AI draft without adding client-specific proof',
        'Letting AI invent outcomes, timelines, guarantees, or pricing logic',
        'Using vague deliverables like "strategy" without defining what the client receives',
        'Hiding assumptions and exclusions until after the client accepts',
        'Forgetting a single clear next step at the end of the proposal'
      ],
      verification: [
        'Client name, project scope, dates, price, taxes, and payment schedule',
        'Claims about previous work, results, certifications, or availability',
        'Legal language, ownership rights, cancellation terms, and revision limits',
        'Any tool-generated promise that sounds like a guaranteed business outcome'
      ]
    };
  }

  if (primaryLower.includes('social media') || primaryLower.includes('content calendar')) {
    return {
      outcomeExamples: [
        'A seven-day Instagram and Facebook calendar for a local bakery promoting weekend specials',
        'Three post angles for a service business that wants calls, not just likes',
        'Caption drafts that reuse real customer questions, offers, and seasonal moments',
        'A weekly review checklist for checking accuracy, tone, and scheduling'
      ],
      toolRows: [
        ['Idea generation', tools[0] || 'LLM', 'Turns offers, FAQs, and events into post angles'],
        ['Scheduling', tools[1] || 'Meta Business Suite', 'Publishes Facebook and Instagram posts from one place'],
        ['Design', tools[2] || 'Canva', 'Creates simple branded visuals without a design team'],
        ['Queue management', tools[3] || 'Buffer', 'Helps keep posts moving when one channel is not enough']
      ],
      steps: [
        {
          title: workflow[0] || 'List offers',
          detail: 'Start with real business inputs: current offers, opening hours, seasonal events, customer questions, photos you already have, and products or services with good margins. AI performs better when it gets raw material from the business instead of guessing what customers care about.',
          prompt: `Create a one-week content input list for a local business. Use these offers, FAQs, events, and customer objections. Group ideas by goal: awareness, trust, direct offer, education, and repeat visit.\n\nBusiness notes:\n[paste notes]`,
          check: 'Remove anything that mentions an offer, date, product, or policy you cannot verify.'
        },
        {
          title: workflow[1] || 'Generate post angles',
          detail: 'Ask AI for angles before full captions. Good angles include customer questions, behind-the-scenes moments, simple comparisons, before-and-after explanations, limited-time offers, and local relevance. Pick the strongest seven before writing captions so the calendar has variety.',
          prompt: `Generate 12 social media post angles from this business input. For each angle, include the target customer, hook, post format, call to action, and why it fits this week. Avoid generic motivational posts.`,
          check: 'Keep a mix of helpful, proof-based, local, and offer-driven posts.'
        },
        {
          title: workflow[2] || 'Write captions',
          detail: 'Now write captions in batches. Give AI the chosen angles, the brand voice, words to avoid, platform, and desired call to action. Ask for shorter captions first; small businesses often need clarity more than cleverness. Save the best lines as reusable caption blocks.',
          prompt: `Write captions for these seven post angles. Keep them clear, local, and useful. Include a short hook, one useful detail, and one call to action. Avoid hype, fake scarcity, and overused AI phrases.`,
          check: 'Read each caption as the business owner. If it sounds like a generic brand, rewrite it.'
        },
        {
          title: workflow[3] || 'Schedule and review',
          detail: 'Before scheduling, check every caption, image, link, tag, and date. Then schedule posts in Meta Business Suite, Buffer, or the tool the business already uses. After the week ends, review which posts got useful actions: messages, calls, saves, comments, or clicks.',
          prompt: `Create a final review checklist for this one-week calendar. Include accuracy checks, visual checks, scheduling checks, and post-week performance notes.`,
          check: 'Do not judge only by likes. Track the action the business actually wanted.'
        }
      ],
      mistakes: [
        'Asking AI for random post ideas without giving offers, FAQs, or local context',
        'Scheduling captions with wrong dates, hours, prices, or unavailable products',
        'Posting seven sales posts in a row with no helpful or trust-building content',
        'Using generic hooks that could belong to any business',
        'Never reviewing which posts created messages, calls, bookings, or visits'
      ],
      verification: [
        'Opening hours, offer dates, menu/service details, prices, addresses, and phone numbers',
        'Image rights, brand colors, logos, and customer photo permissions',
        'Platform rules for promotions, claims, health content, or before-and-after posts',
        'Whether the call to action matches what staff can actually handle that week'
      ]
    };
  }

  return {
    outcomeExamples: [
      `A finished ${primary} asset based on real questions, notes, or business inputs`,
      `A reviewed workflow that ${audience} can repeat without starting from scratch`,
      `A saved prompt template with assumptions and risky claims clearly marked`,
      `A practical checklist for publishing, sending, studying, or handing off the result`
    ],
    toolRows: tools.slice(0, 4).map((tool, index) => [
      workflow[index] || `Workflow stage ${index + 1}`,
      tool,
      [
        'Captures the raw input before AI starts drafting',
        'Keeps the draft editable and easy to review',
        'Helps organize reusable examples, questions, and constraints',
        'Supports the final publish, send, or handoff step'
      ][index] || 'Keeps this stage practical, editable, and easy to verify'
    ]),
    steps: workflow.slice(0, 4).map((step, index) => ({
      title: step,
      detail: [
        `Start by collecting the source material for "${primary}": real notes, customer questions, assignment details, client constraints, examples, and anything that must not be changed. This gives AI a grounded input instead of forcing it to invent context. For ${audience}, the best inputs usually come from repeated questions, support messages, client notes, class requirements, product details, or previous work that already performed well. Do not ask for a draft until those inputs are in one place.`,
        `Group the input into a simple structure before asking for polished writing. For ${audience}, this means separating facts, assumptions, missing details, examples, and the exact output format. A useful structure makes review faster because you can see what came from the source material and what came from the model. If a section has no supporting input, mark it as missing instead of letting AI fill the gap with a confident guess.`,
        `Draft the first usable version with a narrow prompt. Ask AI to mark assumptions, uncertainty, risky claims, and anything that needs a human decision. A good draft should make review easier, not replace review. Keep the output focused on the channel where it will be used, such as a website page, client document, study note, email, or publishing checklist. If the draft tries to solve too many jobs at once, split it into smaller outputs.`,
        `Publish, send, or save the final version only after the verification pass. Store the final prompt and edited output together so the next similar task starts from a proven template.`
      ][index] || `${sentenceCase(step)} should produce a concrete output that can be reviewed and reused.`,
      prompt: [
        `Collect the inputs for this ${primary} workflow. Ask me for missing details, then organize what I provide into facts, assumptions, audience details, constraints, examples, and risks.`,
        `Turn these inputs into a clear structure for ${primary}. Group related items, flag missing information, and recommend the best output format for ${audience}.`,
        `Draft the ${primary} output using the structure below. Keep it practical, specific, and easy to verify. Mark every assumption and every claim that needs checking.`,
        `Create a final review and reuse checklist for this ${primary} workflow. Include accuracy checks, tone checks, formatting checks, and what to save for next time.`
      ][index] || `Help me complete this ${primary} workflow stage: ${step}.`,
      check: [
        'Confirm the source material is real, specific, and safe to use with the chosen tool.',
        'Confirm the structure matches the searcher intent and does not skip key questions.',
        'Confirm the draft contains no invented facts, prices, dates, results, or guarantees.',
        'Confirm the final version is saved with its prompt, checklist, and verified output.'
      ][index] || 'Confirm the output matches your real task, audience, and constraints.'
    })),
    mistakes: [
      'Starting with a vague prompt and expecting a polished result',
      'Using a tool because it is popular instead of because it fits the task',
      'Skipping verification for dates, names, prices, facts, or policies',
      'Saving no reusable template after the work is done'
    ],
    verification: [
      'Tool names, pricing, limits, and terms',
      'Facts, dates, names, numbers, citations, and policy-sensitive claims',
      'Whether the final output matches the audience and channel',
      'Whether private or client data is safe to upload to the chosen tool'
    ]
  };
}

export function buildFallbackPost({ cluster, now = new Date(), existingPosts = [] }) {
  const primary = cluster.primaryKeyword;
  const audience = cluster.audience || 'students and freelancers';
  const intent = cluster.searchIntent || 'informational';
  const secondary = (cluster.secondaryKeywords || []).slice(0, 3);
  const angle = cluster.articleAngle || 'practical implementation guide';
  const plan = buildFallbackPlan({ cluster, primary, audience, angle });
  const workflowSteps = plan.steps.map((step, index) => `## Step ${index + 1}: ${step.title}

${step.detail}

Copy-paste prompt:

\`\`\`
${step.prompt}
\`\`\`

Verification check: ${step.check}`).join('\n\n');
  const toolRows = plan.toolRows.map((row) => `| ${row[0]} | ${row[1]} | ${row[2]} |`).join('\n');

  const baseSlug = cluster.slug || primary.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const slug = baseSlug;

  const title = `${primary} workflow for ${audience}`;
  const metaTitle = `${primary} guide for ${audience}`;
  const metaDescription = `Step-by-step ${primary} workflow for ${audience}. Tools, prompt templates, verification checklist, and common mistakes to avoid.`;
  const excerpt = `A practical ${primary} workflow for ${audience}. Tools, prompt templates, and verification checklist included.`;

  const body = `## ${primary}: the practical answer

People searching for "${primary}" need a usable workflow, not another list of AI tools. The best starting point is simple: collect the real inputs, use AI to shape a draft, verify every changing detail, then save the final version as a reusable template. For ${audience}, this guide focuses on ${angle}.

Search intent: ${intent}. The reader is looking for a concrete process they can follow today, not theoretical explanations.

The recommended workflow is: gather the raw material, draft one focused output, review it against real-world facts, and store the improved version for the next similar task.

## Best ranking angle: ${angle}

The highest-value angle is repeatability. One good AI session should not disappear after the task is done. It should become a template, checklist, or saved prompt that makes the next task faster and more consistent.

Use this workflow when you need one of these concrete outcomes:

${renderBullets(plan.outcomeExamples)}

Most weak AI content fails because it treats the tool as the strategy. The tool is only useful after the task is clear. That is why this guide starts with inputs and verification instead of a giant prompt collection.

## Tool stack for ${primary}

| Workflow stage | Tool to consider | Why it helps |
|----------------|------------------|--------------|
${toolRows}

Start with the tools you already use. Switching apps is rarely the bottleneck. The bottleneck is usually missing context, unclear constraints, or no review process.

${workflowSteps}

Do not move through these steps mechanically. If any draft feels generic, add more source material, examples, constraints, and audience details before asking AI to rewrite it. The workflow should produce something a real person can use without guessing what you meant.

## What to verify before using this workflow

Check the parts that change over time before using this workflow for school, client, or business work:

${renderBullets(plan.verification)}

Also check current pricing and free-tier limits for any tool you mention. Product limits and feature names change often, so avoid building a client or business process around old assumptions.

This verification pass is what separates useful AI-assisted work from risky automation. Keep a short record of what you checked, especially when the output affects a client, customer, school submission, or public business page.

## Reusable prompt template for ${primary}

Copy this structure and fill in your specifics. Save it as a text file for reuse:

\`\`\`
Act as a practical AI workflow assistant for ${audience}.

Task: I need to use ${primary} for [specific outcome].
Audience: [who will read or use the output].
Inputs I have: [notes, links, examples, constraints, offers, dates, client details].
Must include: [required sections, facts, examples, tone, format].
Must avoid: [claims, phrases, details, or formats that would be wrong].

Process:
1. Ask up to 3 clarifying questions if a required detail is missing.
2. Draft the output in the requested format.
3. Mark assumptions and facts that need verification.
4. Give me a final checklist before I use or publish it.
\`\`\`

Key principle: the prompt is a working document. After each use, add the missing constraints that would have improved the first draft.

## Save the verified output as a template

Template structure:

\`\`\`
# Task: [one-line description]
# Prompt: [the refined prompt]
# Verified output: [your corrected version]
# Checklist: [the reusable checklist]
\`\`\`

Store the prompt, final output, and checklist together. Tag it with "${primary}", the audience, the channel, and the use case. Next time, start from the saved version and update only the details that changed.

The saved version should include your edits, not only the original AI draft. That way the template captures your judgment, preferred wording, and known constraints. Over time, this becomes a practical library of proven workflows rather than a folder of raw prompts.

## Common mistakes to avoid

${renderBullets(plan.mistakes)}

Each mistake has a simple fix: add more real context, ask for assumptions to be marked, verify details before use, and keep the final output tied to a clear action.

When the output disappoints you, diagnose the workflow before blaming the tool. Most weak results trace back to missing inputs, unclear audience, no examples, or a skipped review step. Fixing those basics usually improves the next draft immediately.

## Final checklist before publishing or sending

- [ ] Does the output answer the exact search intent or task behind "${primary}"?
- [ ] Is the primary keyword "${primary}" used naturally in the title, H2, meta title, and first 100 words?
- [ ] Are the examples specific to ${audience} instead of generic AI advice?
- [ ] Are all claims verified or marked for human check?
- [ ] Is there a clear next step the reader can take today?
- [ ] Are internal links added to related guides?
- [ ] Is the final version saved as a reusable template?
- [ ] Does the FAQ address real searcher questions?

## Bottom line

${sentenceCase(primary)} works best when it is treated as a repeatable operating process. Define the input, create a focused draft, verify the risky details, and save the improved result. That is what makes the workflow useful beyond one AI chat.

For ranking and reader trust, the same rule applies: publish the specific process, not generic AI enthusiasm. A reader should leave with a prompt they can run, a checklist they can trust, and a clear sense of what still needs human review.

### Related guides on mdevtech Blogs

${existingPosts.length > 0
  ? existingPosts.slice(0, 3).map((p) => `- [${p.title}](/posts/${p.slug}/)`).join('\n')
  : '- [AI tools for students: note-taking and research workflow](/posts/ai-tools-students-note-taking-research/)\n- [AI proposal writing workflow for freelancers](/posts/ai-proposal-writing-freelancers/)\n- [Local business AI content calendar](/posts/ai-content-calendar-local-business/)'}

`;

  const relatedPosts = existingPosts.slice(0, 2).map((p) => ({
    slug: p.slug,
    anchor: p.title
  }));

  // Add fallback internal links if no existing posts
  if (relatedPosts.length < 2) {
    relatedPosts.push(
      { slug: 'ai-tools-students-note-taking-research', anchor: 'AI tools for students: note-taking and research workflow' },
      { slug: 'ai-proposal-writing-freelancers', anchor: 'AI proposal writing workflow for freelancers' }
    );
  }

  return {
    title,
    slug,
    metaTitle,
    metaDescription,
    focusKeywords: [primary, ...secondary.slice(0, 2)],
    searchIntent: intent,
    audience,
    excerpt,
    body,
    faq: [
      {
        question: `What is the best way to use ${primary} effectively?`,
        answer: `Use ${primary} for a specific, repeatable task with clear constraints. Start with the workflow above, verify every output, and save the refined prompt as a template for future use.`
      },
      {
        question: `Can beginners use AI workflows for ${primary} without technical skills?`,
        answer: `Yes. Beginners should start with the prompt template above, use free-tier tools like ChatGPT or Claude, and always verify AI output before relying on it. No coding required.`
      },
      {
        question: `What are the most common mistakes to avoid with ${primary}?`,
        answer: `Avoid vague prompts without context, publishing unverified AI output, targeting generic keywords instead of specific workflows, skipping the human review step, and trying to use five tools when one well-prompted tool suffices.`
      },
      {
        question: `Which tools are best for ${primary} and do I need paid plans?`,
        answer: `Use a general-purpose LLM (ChatGPT, Claude, or Gemini) plus a notes app. All have free tiers sufficient for individual use. Specialized tools like Perplexity or Canva are optional. Verify current free tier limits before relying on them.`
      },
      {
        question: `How long does it take to build and run a ${primary} workflow?`,
        answer: `First time: 30-60 minutes including prompt refinement and verification. After saving as a template: 5-10 minutes per use. The time investment pays off after 2-3 uses.`
      },
      {
        question: `How do I know if my ${primary} output is good enough to use?`,
        answer: `Run the verification checklist: fact-check all tool names and prices, confirm tone matches your voice, ensure every step is actionable, check formatting, and remove any hallucinated features or made-up examples.`
      }
    ],
    internalLinks: relatedPosts.slice(0, 3),
    tags: ['AI automation', audience, primary, 'workflow', 'productivity', 'AI tools'],
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      headline: title,
      description: metaDescription,
      keywords: [primary, ...secondary.slice(0, 2)],
      articleSection: 'AI automation'
    },
    seoScore: 0.9,
    claimsNeedingHumanCheck: [
      'Verify tool names, prices, and feature availability before publishing - free tiers change frequently.',
      'Check that free tier limits mentioned (Zapier, Make, Cursor, etc.) are still accurate as of publication date.',
      'Confirm any statistics or benchmarks cited in the article.',
      'Verify that the prompt template structure works with current model versions.',
      'Ensure internal link slugs match actual published posts.'
    ]
  };
}
